import * as fs from 'fs';
import * as path from 'path';
import { AngularCliWrapper } from '../../ng-cli.wrapper';
import { NameGenerator } from './name.generator';
import { writeDemoFilesToDisk } from './main-demo';

export class OuterComponentGenerator {
  static async generate() {
    const directories = OuterComponentGenerator.getDirectories();
    await OuterComponentGenerator.generateIndex(directories);
    await writeDemoFilesToDisk(OuterComponentGenerator.getInformationAutoGenerated());
    await OuterComponentGenerator.generateDemoRoutes(directories);
  }

  private static async generateDemoRoutes(directories: string[]) {
    const information = OuterComponentGenerator.getInformationAutoGenerated();
    const demoRoutes = OuterComponentGenerator.getDemoRoutes(directories);
    await AngularCliWrapper.createFile('demo/demo.routes.ts', information + demoRoutes);
  }

  private static getDemoRoutes(directories: string[]) {
    return `export const ROUTES = [\n` +
      directories.map((item: string) => {
        const allNames = NameGenerator.generate(item);
        const lazyModule = `../${allNames.demo.folderFullPath}#${allNames.demo.moduleClassName}`;
        return `  { path: '${item}', loadChildren: '${lazyModule}' }`;
      }).join(',\n') + `\n];\n`;
  }

  private static async generateIndex(directories: string[]) {
    const imports = OuterComponentGenerator.getImports(directories);
    const information = OuterComponentGenerator.getInformationAutoGenerated();
    await AngularCliWrapper.createFile('components/index.ts', information + imports);
  }

  private static getImports(directories: string[]): string {
    return directories.map((item: string) => {
      return `export * from './${item}';\n`;
    }).join('');
  }

  private static getDirectories() {
    const srcPath = `${process.cwd()}/src/app/components`;
    return fs.readdirSync(srcPath)
      .filter((file: any) => fs.statSync(path.join(srcPath, file)).isDirectory());
  }

  private static getInformationAutoGenerated() {
    return [
      '/***************************************************************',
      ' ***************************************************************',
      ' ***************** This code was generated by ******************',
      ' **************** angular-cli-library-generator ****************',
      ' * https://www.npmjs.com/package/angular-cli-library-generator *',
      ' ***************************************************************',
      ' ***************************************************************',
      ' ****** Changes to this file may cause incorrect behavior ******',
      ' ********* and will be lost if the code is regenerated *********',
      ' ***************************************************************',
      ' ***************************************************************/\n\n'
    ].join('\n');
  }
}
